spring:
  datasource:
    url: jdbc:h2:~/test;DATABASE_TO_LOWER=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql